-- This script creates a super admin user
-- Auto-generated by setup-superadmin.sh

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM users WHERE username = 'meesum') THEN
    INSERT INTO users (
      id,
      username,
      email,
      password,
      "firstName",
      "lastName",
      roles,
      "isActive",
      "createdAt",
      "updatedAt"
    ) VALUES (
      gen_random_uuid(),
      'meesum',
      'meesum@example.com',
      '$2b$10$QS4jvKDy7chLCeHXgEhcPOEsnO7M.RkxVOhm9hErd4C8COSa19F3G',
      'Super',
      'Admin',
      ARRAY['super_admin']::varchar[],
      true,
      NOW(),
      NOW()
    );
    RAISE NOTICE 'Super admin user created: %', 'meesum';
  ELSE
    UPDATE users
    SET
      email = 'meesum@example.com',
      password = '$2b$10$QS4jvKDy7chLCeHXgEhcPOEsnO7M.RkxVOhm9hErd4C8COSa19F3G',
      roles = ARRAY['super_admin']::varchar[],
      "isActive" = true,
      "updatedAt" = NOW()
    WHERE username = 'meesum';
    RAISE NOTICE 'Super admin user updated: %', 'meesum';
  END IF;
END $$;
